[2025-01-25 09:24:06,678: INFO: common: yaml file: config\config.yaml loaded sucessfully]
[2025-01-25 09:24:06,784: INFO: common: yaml file: params.yaml loaded sucessfully]
[2025-01-25 09:24:40,471: INFO: common: yaml file: config\config.yaml loaded sucessfully]
[2025-01-25 09:24:40,477: INFO: common: yaml file: params.yaml loaded sucessfully]
[2025-01-25 09:24:40,484: INFO: common: yaml file: schema.yaml loaded sucessfully]
[2025-01-25 09:24:40,593: INFO: common: Craeted directory at:artifacts]
[2025-01-25 09:24:40,596: INFO: common: Craeted directory at:artifacts/data_ingestion]
[2025-01-25 09:26:08,830: INFO: 3554620280: artifacts/data_ingestion/data.zip download ! with the following info:
Connection: close
Content-Length: 23329
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "c69888a4ae59bc5a893392785a938ccd4937981c06ba8a9d6a21aa52b4ab5b6e"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: A213:08E2:7A83C:C4ABA:679460D8
Accept-Ranges: bytes
Date: Sat, 25 Jan 2025 03:56:08 GMT
Via: 1.1 varnish
X-Served-By: cache-hyd1100032-HYD
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1737777369.681042,VS0,VE279
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: c2b57030ddd4e3d89f0db100861c797c3884d57e
Expires: Sat, 25 Jan 2025 04:01:08 GMT
Source-Age: 0

]
[2025-01-25 09:45:44,547: INFO: main: >>>>>> stage Data Ingestion Stage started <<<<<<<<]
[2025-01-25 09:45:44,549: INFO: common: yaml file: config\config.yaml loaded sucessfully]
[2025-01-25 09:45:44,550: INFO: common: yaml file: params.yaml loaded sucessfully]
[2025-01-25 09:45:44,550: INFO: common: yaml file: schema.yaml loaded sucessfully]
[2025-01-25 09:45:44,552: INFO: common: Craeted directory at:artifacts]
[2025-01-25 09:45:44,552: INFO: common: Craeted directory at:artifacts/data_ingestion]
[2025-01-25 09:46:27,797: INFO: data_ingestion: artifacts/data_ingestion/data.zip download ! with the following info:
Connection: close
Content-Length: 23329
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "c69888a4ae59bc5a893392785a938ccd4937981c06ba8a9d6a21aa52b4ab5b6e"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: A213:08E2:7A83C:C4ABA:679460D8
Accept-Ranges: bytes
Date: Sat, 25 Jan 2025 04:16:27 GMT
Via: 1.1 varnish
X-Served-By: cache-hyd1100034-HYD
X-Cache: HIT
X-Cache-Hits: 0
X-Timer: S1737778588.598111,VS0,VE286
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: 5854fde2a7514d579f0b6568a5444f21002359b1
Expires: Sat, 25 Jan 2025 04:21:27 GMT
Source-Age: 0

]
[2025-01-25 09:46:27,862: INFO: main: >>>>>> stage Data Ingestion Stage completed <<<<<<<

x============x]
[2025-01-25 10:29:59,999: INFO: common: yaml file: config\config.yaml loaded sucessfully]
[2025-01-25 10:30:00,024: INFO: common: yaml file: params.yaml loaded sucessfully]
[2025-01-25 10:30:00,028: INFO: common: yaml file: schema.yaml loaded sucessfully]
[2025-01-25 10:30:00,044: INFO: common: Craeted directory at:artifacts]
[2025-01-25 10:30:24,527: INFO: common: yaml file: config\config.yaml loaded sucessfully]
[2025-01-25 10:30:24,529: INFO: common: yaml file: params.yaml loaded sucessfully]
[2025-01-25 10:30:24,532: INFO: common: yaml file: schema.yaml loaded sucessfully]
[2025-01-25 10:30:24,533: INFO: common: Craeted directory at:artifacts]
[2025-01-25 10:30:56,715: INFO: common: yaml file: config\config.yaml loaded sucessfully]
[2025-01-25 10:30:56,720: INFO: common: yaml file: params.yaml loaded sucessfully]
[2025-01-25 10:30:56,723: INFO: common: yaml file: schema.yaml loaded sucessfully]
[2025-01-25 10:30:56,725: INFO: common: Craeted directory at:artifacts]
[2025-01-25 10:33:27,421: INFO: common: yaml file: config\config.yaml loaded sucessfully]
[2025-01-25 10:33:27,423: INFO: common: yaml file: params.yaml loaded sucessfully]
[2025-01-25 10:33:27,428: INFO: common: yaml file: schema.yaml loaded sucessfully]
[2025-01-25 10:33:27,430: INFO: common: Craeted directory at:artifacts]
[2025-01-25 10:33:45,649: INFO: common: yaml file: config\config.yaml loaded sucessfully]
[2025-01-25 10:33:45,651: INFO: common: yaml file: params.yaml loaded sucessfully]
[2025-01-25 10:33:45,654: INFO: common: yaml file: schema.yaml loaded sucessfully]
[2025-01-25 10:33:45,655: INFO: common: Craeted directory at:artifacts]
[2025-01-25 10:33:45,657: INFO: common: Craeted directory at:artifacts/data_validation]
[2025-01-25 10:34:15,021: INFO: common: yaml file: config\config.yaml loaded sucessfully]
[2025-01-25 10:34:15,023: INFO: common: yaml file: params.yaml loaded sucessfully]
[2025-01-25 10:34:15,026: INFO: common: yaml file: schema.yaml loaded sucessfully]
[2025-01-25 10:34:15,029: INFO: common: Craeted directory at:artifacts]
[2025-01-25 10:34:15,031: INFO: common: Craeted directory at:artifacts/data_validation]
[2025-01-25 10:52:38,445: INFO: main: >>>>>> stage Data Ingestion Stage started <<<<<<<<]
[2025-01-25 10:52:38,487: INFO: common: yaml file: config\config.yaml loaded sucessfully]
[2025-01-25 10:52:38,488: INFO: common: yaml file: params.yaml loaded sucessfully]
[2025-01-25 10:52:38,492: INFO: common: yaml file: schema.yaml loaded sucessfully]
[2025-01-25 10:52:38,493: INFO: common: Craeted directory at:artifacts]
[2025-01-25 10:52:38,493: INFO: common: Craeted directory at:artifacts/data_ingestion]
[2025-01-25 10:52:38,493: INFO: data_ingestion: File already exists]
[2025-01-25 10:52:38,557: INFO: main: >>>>>> stage Data Ingestion Stage completed <<<<<<<

x============x]
[2025-01-25 10:52:38,557: INFO: main: >>>>>> stage Data Validation Stage started <<<<<<<<]
[2025-01-25 10:52:38,559: INFO: common: yaml file: config\config.yaml loaded sucessfully]
[2025-01-25 10:52:38,559: INFO: common: yaml file: params.yaml loaded sucessfully]
[2025-01-25 10:52:38,561: INFO: common: yaml file: schema.yaml loaded sucessfully]
[2025-01-25 10:52:38,562: INFO: common: Craeted directory at:artifacts]
[2025-01-25 10:52:38,562: INFO: common: Craeted directory at:artifacts/data_validation]
[2025-01-25 10:52:38,592: INFO: main: >>>>>> stage Data Validation Stage completed <<<<<<<

x============x]
[2025-01-25 11:12:00,888: INFO: common: yaml file: config\config.yaml loaded sucessfully]
[2025-01-25 11:12:00,899: INFO: common: yaml file: params.yaml loaded sucessfully]
[2025-01-25 11:12:00,922: INFO: common: yaml file: schema.yaml loaded sucessfully]
[2025-01-25 11:12:00,930: INFO: common: Craeted directory at:artifacts]
[2025-01-25 11:12:00,936: INFO: common: Craeted directory at:artifacts/data_transformation]
[2025-01-25 11:12:37,500: INFO: common: yaml file: config\config.yaml loaded sucessfully]
[2025-01-25 11:12:37,504: INFO: common: yaml file: params.yaml loaded sucessfully]
[2025-01-25 11:12:37,509: INFO: common: yaml file: schema.yaml loaded sucessfully]
[2025-01-25 11:12:37,516: INFO: common: Craeted directory at:artifacts]
[2025-01-25 11:12:37,519: INFO: common: Craeted directory at:artifacts/data_transformation]
[2025-01-25 11:49:08,299: INFO: common: yaml file: config\config.yaml loaded sucessfully]
[2025-01-25 11:49:08,314: INFO: common: yaml file: params.yaml loaded sucessfully]
[2025-01-25 11:49:08,345: INFO: common: yaml file: schema.yaml loaded sucessfully]
[2025-01-25 11:49:08,349: INFO: common: Craeted directory at:artifacts]
[2025-01-25 11:49:08,351: INFO: common: Craeted directory at:artifacts/data_transformation]
[2025-01-25 11:49:08,819: INFO: 328187468: Splitted data into training and test sets]
[2025-01-25 11:49:08,820: INFO: 328187468: (1199, 12)]
[2025-01-25 11:49:08,821: INFO: 328187468: (400, 12)]
[2025-01-25 12:05:45,338: INFO: main: >>>>>> stage Data Ingestion Stage started <<<<<<<<]
[2025-01-25 12:05:45,377: INFO: common: yaml file: config\config.yaml loaded sucessfully]
[2025-01-25 12:05:45,379: INFO: common: yaml file: params.yaml loaded sucessfully]
[2025-01-25 12:05:45,412: INFO: common: yaml file: schema.yaml loaded sucessfully]
[2025-01-25 12:05:45,417: INFO: common: Craeted directory at:artifacts]
[2025-01-25 12:05:45,417: INFO: common: Craeted directory at:artifacts/data_ingestion]
[2025-01-25 12:05:45,418: INFO: data_ingestion: File already exists]
[2025-01-25 12:05:45,513: INFO: main: >>>>>> stage Data Ingestion Stage completed <<<<<<<

x============x]
[2025-01-25 12:05:45,513: INFO: main: >>>>>> stage Data Validation Stage started <<<<<<<<]
[2025-01-25 12:05:45,515: INFO: common: yaml file: config\config.yaml loaded sucessfully]
[2025-01-25 12:05:45,517: INFO: common: yaml file: params.yaml loaded sucessfully]
[2025-01-25 12:05:45,519: INFO: common: yaml file: schema.yaml loaded sucessfully]
[2025-01-25 12:05:45,520: INFO: common: Craeted directory at:artifacts]
[2025-01-25 12:05:45,520: INFO: common: Craeted directory at:artifacts/data_validation]
[2025-01-25 12:05:45,628: INFO: main: >>>>>> stage Data Validation Stage completed <<<<<<<

x============x]
[2025-01-25 12:05:45,628: INFO: main: >>>>>> stage Data Transformation Stage started <<<<<<<<]
[2025-01-25 12:05:45,630: ERROR: data_transformation_pipeline: Your data scheme is not valid]
Traceback (most recent call last):
  File "D:\MLops\End-to-End-DataScienceProject\src\datascience\pipeline\data_transformation_pipeline.py", line 21, in initiate_data_transformation
    raise Exception("Your data scheme is not valid")
Exception: Your data scheme is not valid
[2025-01-25 12:05:45,643: ERROR: main: Your data scheme is not valid]
Traceback (most recent call last):
  File "D:\MLops\End-to-End-DataScienceProject\main.py", line 31, in <module>
    obj.initiate_data_transformation()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "D:\MLops\End-to-End-DataScienceProject\src\datascience\pipeline\data_transformation_pipeline.py", line 24, in initiate_data_transformation
    raise e
  File "D:\MLops\End-to-End-DataScienceProject\src\datascience\pipeline\data_transformation_pipeline.py", line 21, in initiate_data_transformation
    raise Exception("Your data scheme is not valid")
Exception: Your data scheme is not valid
[2025-01-25 12:07:44,646: INFO: main: >>>>>> stage Data Ingestion Stage started <<<<<<<<]
[2025-01-25 12:07:44,648: INFO: common: yaml file: config\config.yaml loaded sucessfully]
[2025-01-25 12:07:44,649: INFO: common: yaml file: params.yaml loaded sucessfully]
[2025-01-25 12:07:44,650: INFO: common: yaml file: schema.yaml loaded sucessfully]
[2025-01-25 12:07:44,651: INFO: common: Craeted directory at:artifacts]
[2025-01-25 12:07:44,652: INFO: common: Craeted directory at:artifacts/data_ingestion]
[2025-01-25 12:07:44,652: INFO: data_ingestion: File already exists]
[2025-01-25 12:07:44,655: INFO: main: >>>>>> stage Data Ingestion Stage completed <<<<<<<

x============x]
[2025-01-25 12:07:44,656: INFO: main: >>>>>> stage Data Validation Stage started <<<<<<<<]
[2025-01-25 12:07:44,659: INFO: common: yaml file: config\config.yaml loaded sucessfully]
[2025-01-25 12:07:44,660: INFO: common: yaml file: params.yaml loaded sucessfully]
[2025-01-25 12:07:44,663: INFO: common: yaml file: schema.yaml loaded sucessfully]
[2025-01-25 12:07:44,664: INFO: common: Craeted directory at:artifacts]
[2025-01-25 12:07:44,665: INFO: common: Craeted directory at:artifacts/data_validation]
[2025-01-25 12:07:44,683: INFO: main: >>>>>> stage Data Validation Stage completed <<<<<<<

x============x]
[2025-01-25 12:07:44,684: INFO: main: >>>>>> stage Data Transformation Stage started <<<<<<<<]
[2025-01-25 12:07:44,685: ERROR: data_transformation_pipeline: Your data scheme is not valid]
Traceback (most recent call last):
  File "D:\MLops\End-to-End-DataScienceProject\src\datascience\pipeline\data_transformation_pipeline.py", line 21, in initiate_data_transformation
    raise Exception("Your data scheme is not valid")
Exception: Your data scheme is not valid
[2025-01-25 12:07:44,686: ERROR: main: Your data scheme is not valid]
Traceback (most recent call last):
  File "D:\MLops\End-to-End-DataScienceProject\main.py", line 31, in <module>
    obj.initiate_data_transformation()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "D:\MLops\End-to-End-DataScienceProject\src\datascience\pipeline\data_transformation_pipeline.py", line 24, in initiate_data_transformation
    raise e
  File "D:\MLops\End-to-End-DataScienceProject\src\datascience\pipeline\data_transformation_pipeline.py", line 21, in initiate_data_transformation
    raise Exception("Your data scheme is not valid")
Exception: Your data scheme is not valid
[2025-01-25 12:07:56,578: INFO: main: >>>>>> stage Data Ingestion Stage started <<<<<<<<]
[2025-01-25 12:07:56,580: INFO: common: yaml file: config\config.yaml loaded sucessfully]
[2025-01-25 12:07:56,581: INFO: common: yaml file: params.yaml loaded sucessfully]
[2025-01-25 12:07:56,582: INFO: common: yaml file: schema.yaml loaded sucessfully]
[2025-01-25 12:07:56,583: INFO: common: Craeted directory at:artifacts]
[2025-01-25 12:07:56,583: INFO: common: Craeted directory at:artifacts/data_ingestion]
[2025-01-25 12:07:56,583: INFO: data_ingestion: File already exists]
[2025-01-25 12:07:56,586: INFO: main: >>>>>> stage Data Ingestion Stage completed <<<<<<<

x============x]
[2025-01-25 12:07:56,587: INFO: main: >>>>>> stage Data Validation Stage started <<<<<<<<]
[2025-01-25 12:07:56,590: INFO: common: yaml file: config\config.yaml loaded sucessfully]
[2025-01-25 12:07:56,590: INFO: common: yaml file: params.yaml loaded sucessfully]
[2025-01-25 12:07:56,593: INFO: common: yaml file: schema.yaml loaded sucessfully]
[2025-01-25 12:07:56,593: INFO: common: Craeted directory at:artifacts]
[2025-01-25 12:07:56,593: INFO: common: Craeted directory at:artifacts/data_validation]
[2025-01-25 12:07:56,679: INFO: main: >>>>>> stage Data Validation Stage completed <<<<<<<

x============x]
[2025-01-25 12:07:56,681: INFO: main: >>>>>> stage Data Transformation Stage started <<<<<<<<]
[2025-01-25 12:07:56,684: ERROR: data_transformation_pipeline: Your data scheme is not valid]
Traceback (most recent call last):
  File "D:\MLops\End-to-End-DataScienceProject\src\datascience\pipeline\data_transformation_pipeline.py", line 21, in initiate_data_transformation
    raise Exception("Your data scheme is not valid")
Exception: Your data scheme is not valid
[2025-01-25 12:07:56,691: ERROR: main: Your data scheme is not valid]
Traceback (most recent call last):
  File "D:\MLops\End-to-End-DataScienceProject\main.py", line 31, in <module>
    obj.initiate_data_transformation()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "D:\MLops\End-to-End-DataScienceProject\src\datascience\pipeline\data_transformation_pipeline.py", line 24, in initiate_data_transformation
    raise e
  File "D:\MLops\End-to-End-DataScienceProject\src\datascience\pipeline\data_transformation_pipeline.py", line 21, in initiate_data_transformation
    raise Exception("Your data scheme is not valid")
Exception: Your data scheme is not valid
[2025-01-25 12:11:10,446: INFO: main: >>>>>> stage Data Ingestion Stage started <<<<<<<<]
[2025-01-25 12:11:10,449: INFO: common: yaml file: config\config.yaml loaded sucessfully]
[2025-01-25 12:11:10,451: INFO: common: yaml file: params.yaml loaded sucessfully]
[2025-01-25 12:11:10,454: INFO: common: yaml file: schema.yaml loaded sucessfully]
[2025-01-25 12:11:10,455: INFO: common: Craeted directory at:artifacts]
[2025-01-25 12:11:10,456: INFO: common: Craeted directory at:artifacts/data_ingestion]
[2025-01-25 12:11:10,457: INFO: data_ingestion: File already exists]
[2025-01-25 12:11:10,461: INFO: main: >>>>>> stage Data Ingestion Stage completed <<<<<<<

x============x]
[2025-01-25 12:11:10,461: INFO: main: >>>>>> stage Data Validation Stage started <<<<<<<<]
[2025-01-25 12:11:10,466: INFO: common: yaml file: config\config.yaml loaded sucessfully]
[2025-01-25 12:11:10,467: INFO: common: yaml file: params.yaml loaded sucessfully]
[2025-01-25 12:11:10,470: INFO: common: yaml file: schema.yaml loaded sucessfully]
[2025-01-25 12:11:10,471: INFO: common: Craeted directory at:artifacts]
[2025-01-25 12:11:10,472: INFO: common: Craeted directory at:artifacts/data_validation]
[2025-01-25 12:11:10,502: INFO: main: >>>>>> stage Data Validation Stage completed <<<<<<<

x============x]
[2025-01-25 12:11:10,503: INFO: main: >>>>>> stage Data Transformation Stage started <<<<<<<<]
[2025-01-25 12:11:10,505: ERROR: data_transformation_pipeline: Your data scheme is not valid]
Traceback (most recent call last):
  File "D:\MLops\End-to-End-DataScienceProject\src\datascience\pipeline\data_transformation_pipeline.py", line 21, in initiate_data_transformation
    raise Exception("Your data scheme is not valid")
Exception: Your data scheme is not valid
[2025-01-25 12:11:10,506: ERROR: main: Your data scheme is not valid]
Traceback (most recent call last):
  File "D:\MLops\End-to-End-DataScienceProject\main.py", line 31, in <module>
    obj.initiate_data_transformation()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "D:\MLops\End-to-End-DataScienceProject\src\datascience\pipeline\data_transformation_pipeline.py", line 24, in initiate_data_transformation
    raise e
  File "D:\MLops\End-to-End-DataScienceProject\src\datascience\pipeline\data_transformation_pipeline.py", line 21, in initiate_data_transformation
    raise Exception("Your data scheme is not valid")
Exception: Your data scheme is not valid
[2025-01-25 12:11:59,672: INFO: main: >>>>>> stage Data Ingestion Stage started <<<<<<<<]
[2025-01-25 12:11:59,674: INFO: common: yaml file: config\config.yaml loaded sucessfully]
[2025-01-25 12:11:59,675: INFO: common: yaml file: params.yaml loaded sucessfully]
[2025-01-25 12:11:59,677: INFO: common: yaml file: schema.yaml loaded sucessfully]
[2025-01-25 12:11:59,677: INFO: common: Craeted directory at:artifacts]
[2025-01-25 12:11:59,677: INFO: common: Craeted directory at:artifacts/data_ingestion]
[2025-01-25 12:13:26,880: INFO: data_ingestion: artifacts/data_ingestion/data.zip download ! with the following info:
Connection: close
Content-Length: 23329
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "c69888a4ae59bc5a893392785a938ccd4937981c06ba8a9d6a21aa52b4ab5b6e"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: D2D8:08FD:2D56B:43532:6794880E
Accept-Ranges: bytes
Date: Sat, 25 Jan 2025 06:43:26 GMT
Via: 1.1 varnish
X-Served-By: cache-hyd1100030-HYD
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1737787407.619947,VS0,VE254
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: 657880e3ccdf5735b98d003f7fca5c71b4e14869
Expires: Sat, 25 Jan 2025 06:48:26 GMT
Source-Age: 0

]
[2025-01-25 12:13:26,905: INFO: main: >>>>>> stage Data Ingestion Stage completed <<<<<<<

x============x]
[2025-01-25 12:13:26,905: INFO: main: >>>>>> stage Data Validation Stage started <<<<<<<<]
[2025-01-25 12:13:26,907: INFO: common: yaml file: config\config.yaml loaded sucessfully]
[2025-01-25 12:13:26,908: INFO: common: yaml file: params.yaml loaded sucessfully]
[2025-01-25 12:13:26,910: INFO: common: yaml file: schema.yaml loaded sucessfully]
[2025-01-25 12:13:26,910: INFO: common: Craeted directory at:artifacts]
[2025-01-25 12:13:26,912: INFO: common: Craeted directory at:artifacts/data_validation]
[2025-01-25 12:13:26,935: INFO: main: >>>>>> stage Data Validation Stage completed <<<<<<<

x============x]
[2025-01-25 12:13:26,935: INFO: main: >>>>>> stage Data Transformation Stage started <<<<<<<<]
[2025-01-25 12:13:26,937: ERROR: data_transformation_pipeline: Your data scheme is not valid]
Traceback (most recent call last):
  File "D:\MLops\End-to-End-DataScienceProject\src\datascience\pipeline\data_transformation_pipeline.py", line 21, in initiate_data_transformation
    raise Exception("Your data scheme is not valid")
Exception: Your data scheme is not valid
[2025-01-25 12:13:26,938: ERROR: main: Your data scheme is not valid]
Traceback (most recent call last):
  File "D:\MLops\End-to-End-DataScienceProject\main.py", line 31, in <module>
    obj.initiate_data_transformation()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "D:\MLops\End-to-End-DataScienceProject\src\datascience\pipeline\data_transformation_pipeline.py", line 24, in initiate_data_transformation
    raise e
  File "D:\MLops\End-to-End-DataScienceProject\src\datascience\pipeline\data_transformation_pipeline.py", line 21, in initiate_data_transformation
    raise Exception("Your data scheme is not valid")
Exception: Your data scheme is not valid
[2025-01-25 12:14:10,121: INFO: main: >>>>>> stage Data Ingestion Stage started <<<<<<<<]
[2025-01-25 12:14:10,123: INFO: common: yaml file: config\config.yaml loaded sucessfully]
[2025-01-25 12:14:10,124: INFO: common: yaml file: params.yaml loaded sucessfully]
[2025-01-25 12:14:10,130: INFO: common: yaml file: schema.yaml loaded sucessfully]
[2025-01-25 12:14:10,131: INFO: common: Craeted directory at:artifacts]
[2025-01-25 12:14:10,131: INFO: common: Craeted directory at:artifacts/data_ingestion]
[2025-01-25 12:14:10,132: INFO: data_ingestion: File already exists]
[2025-01-25 12:14:10,135: INFO: main: >>>>>> stage Data Ingestion Stage completed <<<<<<<

x============x]
[2025-01-25 12:14:10,136: INFO: main: >>>>>> stage Data Validation Stage started <<<<<<<<]
[2025-01-25 12:14:10,139: INFO: common: yaml file: config\config.yaml loaded sucessfully]
[2025-01-25 12:14:10,142: INFO: common: yaml file: params.yaml loaded sucessfully]
[2025-01-25 12:14:10,144: INFO: common: yaml file: schema.yaml loaded sucessfully]
[2025-01-25 12:14:10,145: INFO: common: Craeted directory at:artifacts]
[2025-01-25 12:14:10,146: INFO: common: Craeted directory at:artifacts/data_validation]
[2025-01-25 12:14:10,168: INFO: main: >>>>>> stage Data Validation Stage completed <<<<<<<

x============x]
[2025-01-25 12:14:10,169: INFO: main: >>>>>> stage Data Transformation Stage started <<<<<<<<]
[2025-01-25 12:14:10,178: ERROR: data_transformation_pipeline: Your data scheme is not valid]
Traceback (most recent call last):
  File "D:\MLops\End-to-End-DataScienceProject\src\datascience\pipeline\data_transformation_pipeline.py", line 21, in initiate_data_transformation
    raise Exception("Your data scheme is not valid")
Exception: Your data scheme is not valid
[2025-01-25 12:14:10,179: ERROR: main: Your data scheme is not valid]
Traceback (most recent call last):
  File "D:\MLops\End-to-End-DataScienceProject\main.py", line 31, in <module>
    obj.initiate_data_transformation()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "D:\MLops\End-to-End-DataScienceProject\src\datascience\pipeline\data_transformation_pipeline.py", line 24, in initiate_data_transformation
    raise e
  File "D:\MLops\End-to-End-DataScienceProject\src\datascience\pipeline\data_transformation_pipeline.py", line 21, in initiate_data_transformation
    raise Exception("Your data scheme is not valid")
Exception: Your data scheme is not valid
[2025-01-25 12:14:42,167: INFO: main: >>>>>> stage Data Ingestion Stage started <<<<<<<<]
[2025-01-25 12:14:42,170: INFO: common: yaml file: config\config.yaml loaded sucessfully]
[2025-01-25 12:14:42,170: INFO: common: yaml file: params.yaml loaded sucessfully]
[2025-01-25 12:14:42,172: INFO: common: yaml file: schema.yaml loaded sucessfully]
[2025-01-25 12:14:42,173: INFO: common: Craeted directory at:artifacts]
[2025-01-25 12:14:42,173: INFO: common: Craeted directory at:artifacts/data_ingestion]
[2025-01-25 12:16:07,161: INFO: data_ingestion: artifacts/data_ingestion/data.zip download ! with the following info:
Connection: close
Content-Length: 23329
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "c69888a4ae59bc5a893392785a938ccd4937981c06ba8a9d6a21aa52b4ab5b6e"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: D2D8:08FD:2D56B:43532:6794880E
Accept-Ranges: bytes
Date: Sat, 25 Jan 2025 06:46:07 GMT
Via: 1.1 varnish
X-Served-By: cache-hyd1100025-HYD
X-Cache: HIT
X-Cache-Hits: 0
X-Timer: S1737787567.124300,VS0,VE100
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: d8e6b366984e5c201fb01755890389d916107b60
Expires: Sat, 25 Jan 2025 06:51:07 GMT
Source-Age: 160

]
[2025-01-25 12:16:08,831: INFO: main: >>>>>> stage Data Ingestion Stage completed <<<<<<<

x============x]
[2025-01-25 12:16:08,833: INFO: main: >>>>>> stage Data Validation Stage started <<<<<<<<]
[2025-01-25 12:16:08,840: INFO: common: yaml file: config\config.yaml loaded sucessfully]
[2025-01-25 12:16:08,843: INFO: common: yaml file: params.yaml loaded sucessfully]
[2025-01-25 12:16:08,855: INFO: common: yaml file: schema.yaml loaded sucessfully]
[2025-01-25 12:16:08,856: INFO: common: Craeted directory at:artifacts]
[2025-01-25 12:16:08,857: INFO: common: Craeted directory at:artifacts/data_validation]
[2025-01-25 12:16:08,884: INFO: main: >>>>>> stage Data Validation Stage completed <<<<<<<

x============x]
[2025-01-25 12:16:08,885: INFO: main: >>>>>> stage Data Transformation Stage started <<<<<<<<]
[2025-01-25 12:16:08,886: ERROR: data_transformation_pipeline: Your data scheme is not valid]
Traceback (most recent call last):
  File "D:\MLops\End-to-End-DataScienceProject\src\datascience\pipeline\data_transformation_pipeline.py", line 21, in initiate_data_transformation
    raise Exception("Your data scheme is not valid")
Exception: Your data scheme is not valid
[2025-01-25 12:16:08,888: ERROR: main: Your data scheme is not valid]
Traceback (most recent call last):
  File "D:\MLops\End-to-End-DataScienceProject\main.py", line 31, in <module>
    obj.initiate_data_transformation()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "D:\MLops\End-to-End-DataScienceProject\src\datascience\pipeline\data_transformation_pipeline.py", line 24, in initiate_data_transformation
    raise e
  File "D:\MLops\End-to-End-DataScienceProject\src\datascience\pipeline\data_transformation_pipeline.py", line 21, in initiate_data_transformation
    raise Exception("Your data scheme is not valid")
Exception: Your data scheme is not valid
[2025-01-25 12:18:29,851: INFO: main: >>>>>> stage Data Ingestion Stage started <<<<<<<<]
[2025-01-25 12:18:29,853: INFO: common: yaml file: config\config.yaml loaded sucessfully]
[2025-01-25 12:18:29,854: INFO: common: yaml file: params.yaml loaded sucessfully]
[2025-01-25 12:18:29,856: INFO: common: yaml file: schema.yaml loaded sucessfully]
[2025-01-25 12:18:29,857: INFO: common: Craeted directory at:artifacts]
[2025-01-25 12:18:29,858: INFO: common: Craeted directory at:artifacts/data_ingestion]
[2025-01-25 12:18:29,858: INFO: data_ingestion: File already exists]
[2025-01-25 12:18:29,860: INFO: main: >>>>>> stage Data Ingestion Stage completed <<<<<<<

x============x]
[2025-01-25 12:18:29,861: INFO: main: >>>>>> stage Data Validation Stage started <<<<<<<<]
[2025-01-25 12:18:29,862: INFO: common: yaml file: config\config.yaml loaded sucessfully]
[2025-01-25 12:18:29,863: INFO: common: yaml file: params.yaml loaded sucessfully]
[2025-01-25 12:18:29,865: INFO: common: yaml file: schema.yaml loaded sucessfully]
[2025-01-25 12:18:29,866: INFO: common: Craeted directory at:artifacts]
[2025-01-25 12:18:29,866: INFO: common: Craeted directory at:artifacts/data_validation]
[2025-01-25 12:18:29,889: INFO: main: >>>>>> stage Data Validation Stage completed <<<<<<<

x============x]
[2025-01-25 12:18:29,889: INFO: main: >>>>>> stage Data Transformation Stage started <<<<<<<<]
[2025-01-25 12:18:29,890: ERROR: data_transformation_pipeline: Your data scheme is not valid]
Traceback (most recent call last):
  File "D:\MLops\End-to-End-DataScienceProject\src\datascience\pipeline\data_transformation_pipeline.py", line 22, in initiate_data_transformation
    raise Exception("Your data scheme is not valid")
Exception: Your data scheme is not valid
[2025-01-25 12:18:29,891: ERROR: main: Your data scheme is not valid]
Traceback (most recent call last):
  File "D:\MLops\End-to-End-DataScienceProject\main.py", line 31, in <module>
    obj.initiate_data_transformation()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "D:\MLops\End-to-End-DataScienceProject\src\datascience\pipeline\data_transformation_pipeline.py", line 25, in initiate_data_transformation
    raise e
  File "D:\MLops\End-to-End-DataScienceProject\src\datascience\pipeline\data_transformation_pipeline.py", line 22, in initiate_data_transformation
    raise Exception("Your data scheme is not valid")
Exception: Your data scheme is not valid
[2025-01-25 12:20:47,621: INFO: main: >>>>>> stage Data Ingestion Stage started <<<<<<<<]
[2025-01-25 12:20:47,623: INFO: common: yaml file: config\config.yaml loaded sucessfully]
[2025-01-25 12:20:47,624: INFO: common: yaml file: params.yaml loaded sucessfully]
[2025-01-25 12:20:47,626: INFO: common: yaml file: schema.yaml loaded sucessfully]
[2025-01-25 12:20:47,627: INFO: common: Craeted directory at:artifacts]
[2025-01-25 12:20:47,627: INFO: common: Craeted directory at:artifacts/data_ingestion]
[2025-01-25 12:22:12,615: INFO: data_ingestion: artifacts/data_ingestion/data.zip download ! with the following info:
Connection: close
Content-Length: 23329
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "c69888a4ae59bc5a893392785a938ccd4937981c06ba8a9d6a21aa52b4ab5b6e"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: D2D8:08FD:2D56B:43532:6794880E
Accept-Ranges: bytes
Date: Sat, 25 Jan 2025 06:52:12 GMT
Via: 1.1 varnish
X-Served-By: cache-hyd1100026-HYD
X-Cache: HIT
X-Cache-Hits: 0
X-Timer: S1737787932.423723,VS0,VE242
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: 1236a813bcb3f5045bfe0072d39716ff62718256
Expires: Sat, 25 Jan 2025 06:57:12 GMT
Source-Age: 0

]
[2025-01-25 12:22:12,652: INFO: main: >>>>>> stage Data Ingestion Stage completed <<<<<<<

x============x]
[2025-01-25 12:22:12,653: INFO: main: >>>>>> stage Data Validation Stage started <<<<<<<<]
[2025-01-25 12:22:12,655: INFO: common: yaml file: config\config.yaml loaded sucessfully]
[2025-01-25 12:22:12,656: INFO: common: yaml file: params.yaml loaded sucessfully]
[2025-01-25 12:22:12,658: INFO: common: yaml file: schema.yaml loaded sucessfully]
[2025-01-25 12:22:12,659: INFO: common: Craeted directory at:artifacts]
[2025-01-25 12:22:12,660: INFO: common: Craeted directory at:artifacts/data_validation]
[2025-01-25 12:22:12,679: INFO: main: >>>>>> stage Data Validation Stage completed <<<<<<<

x============x]
[2025-01-25 12:22:12,680: INFO: main: >>>>>> stage Data Transformation Stage started <<<<<<<<]
[2025-01-25 12:22:12,682: ERROR: data_transformation_pipeline: Your data scheme is not valid]
Traceback (most recent call last):
  File "D:\MLops\End-to-End-DataScienceProject\src\datascience\pipeline\data_transformation_pipeline.py", line 22, in initiate_data_transformation
    raise Exception("Your data scheme is not valid")
Exception: Your data scheme is not valid
[2025-01-25 12:22:12,683: ERROR: main: Your data scheme is not valid]
Traceback (most recent call last):
  File "D:\MLops\End-to-End-DataScienceProject\main.py", line 31, in <module>
    obj.initiate_data_transformation()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "D:\MLops\End-to-End-DataScienceProject\src\datascience\pipeline\data_transformation_pipeline.py", line 25, in initiate_data_transformation
    raise e
  File "D:\MLops\End-to-End-DataScienceProject\src\datascience\pipeline\data_transformation_pipeline.py", line 22, in initiate_data_transformation
    raise Exception("Your data scheme is not valid")
Exception: Your data scheme is not valid
[2025-01-25 12:26:22,134: INFO: main: >>>>>> stage Data Ingestion Stage started <<<<<<<<]
[2025-01-25 12:26:22,136: INFO: common: yaml file: config\config.yaml loaded sucessfully]
[2025-01-25 12:26:22,137: INFO: common: yaml file: params.yaml loaded sucessfully]
[2025-01-25 12:26:22,139: INFO: common: yaml file: schema.yaml loaded sucessfully]
[2025-01-25 12:26:22,140: INFO: common: Craeted directory at:artifacts]
[2025-01-25 12:26:22,141: INFO: common: Craeted directory at:artifacts/data_ingestion]
[2025-01-25 12:26:22,141: INFO: data_ingestion: File already exists]
[2025-01-25 12:26:22,144: INFO: main: >>>>>> stage Data Ingestion Stage completed <<<<<<<

x============x]
[2025-01-25 12:26:22,145: INFO: main: >>>>>> stage Data Validation Stage started <<<<<<<<]
[2025-01-25 12:26:22,147: INFO: common: yaml file: config\config.yaml loaded sucessfully]
[2025-01-25 12:26:22,149: INFO: common: yaml file: params.yaml loaded sucessfully]
[2025-01-25 12:26:22,154: INFO: common: yaml file: schema.yaml loaded sucessfully]
[2025-01-25 12:26:22,155: INFO: common: Craeted directory at:artifacts]
[2025-01-25 12:26:22,155: INFO: common: Craeted directory at:artifacts/data_validation]
[2025-01-25 12:26:22,176: INFO: main: >>>>>> stage Data Validation Stage completed <<<<<<<

x============x]
[2025-01-25 12:26:22,177: INFO: main: >>>>>> stage Data Transformation Stage started <<<<<<<<]
[2025-01-25 12:26:22,182: INFO: common: yaml file: config\config.yaml loaded sucessfully]
[2025-01-25 12:26:22,183: INFO: common: yaml file: params.yaml loaded sucessfully]
[2025-01-25 12:26:22,185: INFO: common: yaml file: schema.yaml loaded sucessfully]
[2025-01-25 12:26:22,186: INFO: common: Craeted directory at:artifacts]
[2025-01-25 12:26:22,187: INFO: common: Craeted directory at:artifacts/data_transformation]
[2025-01-25 12:26:22,528: INFO: data_transformation: Splitted data into training and test sets]
[2025-01-25 12:26:22,529: INFO: data_transformation: (1199, 12)]
[2025-01-25 12:26:22,530: INFO: data_transformation: (400, 12)]
[2025-01-25 12:26:22,532: INFO: main: >>>>>> stage Data Transformation Stage completed <<<<<<<

x============x]
[2025-01-25 14:24:09,144: INFO: common: yaml file: config\config.yaml loaded sucessfully]
[2025-01-25 14:24:09,163: INFO: common: yaml file: params.yaml loaded sucessfully]
[2025-01-25 14:24:09,167: INFO: common: yaml file: schema.yaml loaded sucessfully]
[2025-01-25 14:24:09,171: INFO: common: Craeted directory at:artifacts]
[2025-01-25 14:24:09,659: ERROR: 1666941101: got an unexpected keyword argument 'squared']
[2025-01-25 14:25:29,087: INFO: common: yaml file: config\config.yaml loaded sucessfully]
[2025-01-25 14:25:29,090: INFO: common: yaml file: params.yaml loaded sucessfully]
[2025-01-25 14:25:29,092: INFO: common: yaml file: schema.yaml loaded sucessfully]
[2025-01-25 14:25:29,094: INFO: common: Craeted directory at:artifacts]
[2025-01-25 14:25:29,096: INFO: common: Craeted directory at:artifacts]
[2025-01-25 14:25:29,126: ERROR: 1666941101: got an unexpected keyword argument 'squared']
[2025-01-25 14:29:09,865: INFO: common: yaml file: config\config.yaml loaded sucessfully]
[2025-01-25 14:29:09,868: INFO: common: yaml file: params.yaml loaded sucessfully]
[2025-01-25 14:29:09,871: INFO: common: yaml file: schema.yaml loaded sucessfully]
[2025-01-25 14:29:09,873: INFO: common: Craeted directory at:artifacts]
[2025-01-25 14:29:09,874: INFO: common: Craeted directory at:artifacts]
[2025-01-25 14:29:09,886: ERROR: 1666941101: [Errno 2] No such file or directory: 'artifacts/model_trainer\\model.joblib']
[2025-01-25 14:29:22,759: INFO: common: yaml file: config\config.yaml loaded sucessfully]
[2025-01-25 14:29:22,762: INFO: common: yaml file: params.yaml loaded sucessfully]
[2025-01-25 14:29:22,768: INFO: common: yaml file: schema.yaml loaded sucessfully]
[2025-01-25 14:29:22,771: INFO: common: Craeted directory at:artifacts]
[2025-01-25 14:29:22,773: INFO: common: Craeted directory at:artifacts]
[2025-01-25 14:29:22,791: ERROR: 1666941101: [Errno 2] No such file or directory: 'artifacts/model_trainer\\model.joblib']
[2025-01-25 14:31:10,945: INFO: common: yaml file: config\config.yaml loaded sucessfully]
[2025-01-25 14:31:10,948: INFO: common: yaml file: params.yaml loaded sucessfully]
[2025-01-25 14:31:10,953: INFO: common: yaml file: schema.yaml loaded sucessfully]
[2025-01-25 14:31:10,958: INFO: common: Craeted directory at:artifacts]
[2025-01-25 14:31:12,519: ERROR: 1666941101: "'ConfigBox' object has no attribute 'root_dir'"]
[2025-01-25 14:33:18,215: INFO: common: yaml file: config\config.yaml loaded sucessfully]
[2025-01-25 14:33:18,219: INFO: common: yaml file: params.yaml loaded sucessfully]
[2025-01-25 14:33:18,225: INFO: common: yaml file: schema.yaml loaded sucessfully]
[2025-01-25 14:33:18,227: INFO: common: Craeted directory at:artifacts]
[2025-01-25 14:33:19,845: INFO: common: Craeted directory at:artifacts/model_trainer]
[2025-01-25 14:33:19,922: INFO: 2874944050: Model is saved at artifacts/model_trainer]
[2025-01-25 14:44:35,023: INFO: main: >>>>>> stage Data Ingestion Stage started <<<<<<<<]
[2025-01-25 14:44:35,040: INFO: common: yaml file: config\config.yaml loaded sucessfully]
[2025-01-25 14:44:35,043: INFO: common: yaml file: params.yaml loaded sucessfully]
[2025-01-25 14:44:35,048: INFO: common: yaml file: schema.yaml loaded sucessfully]
[2025-01-25 14:44:35,050: INFO: common: Craeted directory at:artifacts]
[2025-01-25 14:44:35,051: INFO: common: Craeted directory at:artifacts/data_ingestion]
[2025-01-25 14:44:35,052: INFO: data_ingestion: File already exists]
[2025-01-25 14:44:35,105: INFO: main: >>>>>> stage Data Ingestion Stage completed <<<<<<<

x============x]
[2025-01-25 14:44:35,105: INFO: main: >>>>>> stage Data Validation Stage started <<<<<<<<]
[2025-01-25 14:44:35,108: INFO: common: yaml file: config\config.yaml loaded sucessfully]
[2025-01-25 14:44:35,110: INFO: common: yaml file: params.yaml loaded sucessfully]
[2025-01-25 14:44:35,115: INFO: common: yaml file: schema.yaml loaded sucessfully]
[2025-01-25 14:44:35,117: INFO: common: Craeted directory at:artifacts]
[2025-01-25 14:44:35,118: INFO: common: Craeted directory at:artifacts/data_validation]
[2025-01-25 14:44:35,157: INFO: main: >>>>>> stage Data Validation Stage completed <<<<<<<

x============x]
[2025-01-25 14:44:35,158: INFO: main: >>>>>> stage Data Transformation Stage started <<<<<<<<]
[2025-01-25 14:44:35,165: INFO: common: yaml file: config\config.yaml loaded sucessfully]
[2025-01-25 14:44:35,167: INFO: common: yaml file: params.yaml loaded sucessfully]
[2025-01-25 14:44:35,170: INFO: common: yaml file: schema.yaml loaded sucessfully]
[2025-01-25 14:44:35,171: INFO: common: Craeted directory at:artifacts]
[2025-01-25 14:44:35,172: INFO: common: Craeted directory at:artifacts/data_transformation]
[2025-01-25 14:44:35,276: INFO: data_transformation: Splitted data into training and test sets]
[2025-01-25 14:44:35,276: INFO: data_transformation: (1199, 12)]
[2025-01-25 14:44:35,277: INFO: data_transformation: (400, 12)]
[2025-01-25 14:44:35,278: INFO: main: >>>>>> stage Data Transformation Stage completed <<<<<<<

x============x]
[2025-01-25 14:44:35,278: INFO: main: >>>>>>>>>>> stageModel Trainer stage STARTED <<<<<<<<<<<]
[2025-01-25 14:44:35,285: INFO: common: yaml file: config\config.yaml loaded sucessfully]
[2025-01-25 14:44:35,287: INFO: common: yaml file: params.yaml loaded sucessfully]
[2025-01-25 14:44:35,292: INFO: common: yaml file: schema.yaml loaded sucessfully]
[2025-01-25 14:44:35,293: INFO: common: Craeted directory at:artifacts]
[2025-01-25 14:44:35,294: INFO: common: Craeted directory at:artifacts/model_trainer]
[2025-01-25 14:44:35,364: INFO: model_trainer: Model is saved at artifacts/model_trainer]
[2025-01-25 14:44:35,364: INFO: main: >>>>>>>> stageModel Trainer stage Completed <<<<<<

x============x]
[2025-01-25 15:26:47,002: INFO: common: yaml file: config\config.yaml loaded sucessfully]
[2025-01-25 15:26:47,004: INFO: common: yaml file: params.yaml loaded sucessfully]
[2025-01-25 15:26:47,013: INFO: common: yaml file: schema.yaml loaded sucessfully]
[2025-01-25 15:26:47,015: ERROR: 3808019970: 'WindowsPath' object has no attribute 'artifacts_root']
[2025-01-25 15:27:28,767: INFO: common: yaml file: config\config.yaml loaded sucessfully]
[2025-01-25 15:27:28,770: INFO: common: yaml file: params.yaml loaded sucessfully]
[2025-01-25 15:27:28,773: INFO: common: yaml file: schema.yaml loaded sucessfully]
[2025-01-25 15:27:28,775: ERROR: 3808019970: 'WindowsPath' object has no attribute 'artifacts_dir']
[2025-01-25 15:28:43,642: INFO: common: yaml file: config\config.yaml loaded sucessfully]
[2025-01-25 15:28:43,644: INFO: common: yaml file: params.yaml loaded sucessfully]
[2025-01-25 15:28:43,648: INFO: common: yaml file: schema.yaml loaded sucessfully]
[2025-01-25 15:28:43,650: ERROR: 3808019970: 'WindowsPath' object has no attribute 'artifacts_root']
[2025-01-25 15:29:16,620: INFO: common: yaml file: config\config.yaml loaded sucessfully]
[2025-01-25 15:29:16,622: INFO: common: yaml file: params.yaml loaded sucessfully]
[2025-01-25 15:29:16,626: INFO: common: yaml file: schema.yaml loaded sucessfully]
[2025-01-25 15:29:16,628: INFO: common: Craeted directory at:artifacts]
[2025-01-25 15:29:16,629: ERROR: 3808019970: 'WindowsPath' object has no attribute 'model_evaluation']
[2025-01-25 15:30:20,528: INFO: common: yaml file: config\config.yaml loaded sucessfully]
[2025-01-25 15:30:20,532: INFO: common: yaml file: params.yaml loaded sucessfully]
[2025-01-25 15:30:20,534: INFO: common: yaml file: schema.yaml loaded sucessfully]
[2025-01-25 15:30:20,536: INFO: common: Craeted directory at:artifacts]
[2025-01-25 15:30:20,537: INFO: common: Craeted directory at:artifacts/model_evaluation]
[2025-01-25 15:30:23,796: ERROR: 3808019970: Argument path of type <class 'dict'> to <function save_jason at 0x00000154C148A160> does not match annotation type <class 'pathlib._local.Path'>]
[2025-01-25 15:31:50,667: INFO: common: yaml file: config\config.yaml loaded sucessfully]
[2025-01-25 15:31:50,673: INFO: common: yaml file: params.yaml loaded sucessfully]
[2025-01-25 15:31:50,677: INFO: common: yaml file: schema.yaml loaded sucessfully]
[2025-01-25 15:31:50,680: INFO: common: Craeted directory at:artifacts]
[2025-01-25 15:31:50,681: INFO: common: Craeted directory at:artifacts/model_evaluation]
[2025-01-25 15:31:51,323: INFO: common: json file saved at:artifacts\model_evaluation\metrics.json]
[2025-01-25 15:46:59,899: INFO: main: >>>>>> stage Data Ingestion Stage started <<<<<<<<]
[2025-01-25 15:46:59,940: INFO: common: yaml file: config\config.yaml loaded sucessfully]
[2025-01-25 15:46:59,942: INFO: common: yaml file: params.yaml loaded sucessfully]
[2025-01-25 15:46:59,947: INFO: common: yaml file: schema.yaml loaded sucessfully]
[2025-01-25 15:46:59,949: INFO: common: Craeted directory at:artifacts]
[2025-01-25 15:46:59,952: INFO: common: Craeted directory at:artifacts/data_ingestion]
[2025-01-25 15:46:59,953: INFO: data_ingestion: File already exists]
[2025-01-25 15:46:59,976: INFO: main: >>>>>> stage Data Ingestion Stage completed <<<<<<<

x============x]
[2025-01-25 15:46:59,978: INFO: main: >>>>>> stage Data Validation Stage started <<<<<<<<]
[2025-01-25 15:46:59,988: INFO: common: yaml file: config\config.yaml loaded sucessfully]
[2025-01-25 15:46:59,996: INFO: common: yaml file: params.yaml loaded sucessfully]
[2025-01-25 15:47:00,000: INFO: common: yaml file: schema.yaml loaded sucessfully]
[2025-01-25 15:47:00,002: INFO: common: Craeted directory at:artifacts]
[2025-01-25 15:47:00,004: INFO: common: Craeted directory at:artifacts/data_validation]
[2025-01-25 15:47:00,129: INFO: main: >>>>>> stage Data Validation Stage completed <<<<<<<

x============x]
[2025-01-25 15:47:00,133: INFO: main: >>>>>> stage Data Transformation Stage started <<<<<<<<]
[2025-01-25 15:47:00,180: INFO: common: yaml file: config\config.yaml loaded sucessfully]
[2025-01-25 15:47:00,183: INFO: common: yaml file: params.yaml loaded sucessfully]
[2025-01-25 15:47:00,196: INFO: common: yaml file: schema.yaml loaded sucessfully]
[2025-01-25 15:47:00,200: INFO: common: Craeted directory at:artifacts]
[2025-01-25 15:47:00,201: INFO: common: Craeted directory at:artifacts/data_transformation]
[2025-01-25 15:47:00,440: INFO: data_transformation: Splitted data into training and test sets]
[2025-01-25 15:47:00,443: INFO: data_transformation: (1199, 12)]
[2025-01-25 15:47:00,445: INFO: data_transformation: (400, 12)]
[2025-01-25 15:47:00,453: INFO: main: >>>>>> stage Data Transformation Stage completed <<<<<<<

x============x]
[2025-01-25 15:47:00,457: INFO: main: >>>>>>>>>>> stageModel Trainer stage STARTED <<<<<<<<<<<]
[2025-01-25 15:47:00,481: INFO: common: yaml file: config\config.yaml loaded sucessfully]
[2025-01-25 15:47:00,485: INFO: common: yaml file: params.yaml loaded sucessfully]
[2025-01-25 15:47:00,496: INFO: common: yaml file: schema.yaml loaded sucessfully]
[2025-01-25 15:47:00,500: INFO: common: Craeted directory at:artifacts]
[2025-01-25 15:47:00,513: INFO: common: Craeted directory at:artifacts/model_trainer]
[2025-01-25 15:47:01,166: INFO: model_trainer: Model is saved at artifacts/model_trainer]
[2025-01-25 15:47:01,167: INFO: main: >>>>>>>> stageModel Trainer stage Completed <<<<<<

x============x]
[2025-01-25 15:47:01,169: INFO: main: >>>>>>>>>>> stageModel Evaluation stage STARTED <<<<<<<<<<<]
[2025-01-25 15:47:01,185: INFO: common: yaml file: config\config.yaml loaded sucessfully]
[2025-01-25 15:47:01,210: INFO: common: yaml file: params.yaml loaded sucessfully]
[2025-01-25 15:47:01,231: INFO: common: yaml file: schema.yaml loaded sucessfully]
[2025-01-25 15:47:01,247: INFO: common: Craeted directory at:artifacts]
[2025-01-25 15:47:01,293: INFO: common: Craeted directory at:artifacts/model_evaluation]
[2025-01-25 15:47:06,689: ERROR: main: name 'Path' is not defined]
Traceback (most recent call last):
  File "D:\MLops\End-to-End-DataScienceProject\main.py", line 57, in <module>
    obj.initiate_model_Evaluation()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "D:\MLops\End-to-End-DataScienceProject\src\datascience\pipeline\model_evaluation_pipeline.py", line 17, in initiate_model_Evaluation
    model_evaluation_config.log_into_mlflow()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "D:\MLops\End-to-End-DataScienceProject\src\datascience\components\model_evaluation.py", line 45, in log_into_mlflow
    save_jason(path=Path(self.config.metric_file_name), data=scores)
                    ^^^^
NameError: name 'Path' is not defined
[2025-01-25 15:48:13,065: INFO: main: >>>>>> stage Data Ingestion Stage started <<<<<<<<]
[2025-01-25 15:48:13,068: INFO: common: yaml file: config\config.yaml loaded sucessfully]
[2025-01-25 15:48:13,069: INFO: common: yaml file: params.yaml loaded sucessfully]
[2025-01-25 15:48:13,071: INFO: common: yaml file: schema.yaml loaded sucessfully]
[2025-01-25 15:48:13,072: INFO: common: Craeted directory at:artifacts]
[2025-01-25 15:48:13,072: INFO: common: Craeted directory at:artifacts/data_ingestion]
[2025-01-25 15:48:13,073: INFO: data_ingestion: File already exists]
[2025-01-25 15:48:13,077: INFO: main: >>>>>> stage Data Ingestion Stage completed <<<<<<<

x============x]
[2025-01-25 15:48:13,077: INFO: main: >>>>>> stage Data Validation Stage started <<<<<<<<]
[2025-01-25 15:48:13,084: INFO: common: yaml file: config\config.yaml loaded sucessfully]
[2025-01-25 15:48:13,086: INFO: common: yaml file: params.yaml loaded sucessfully]
[2025-01-25 15:48:13,088: INFO: common: yaml file: schema.yaml loaded sucessfully]
[2025-01-25 15:48:13,089: INFO: common: Craeted directory at:artifacts]
[2025-01-25 15:48:13,090: INFO: common: Craeted directory at:artifacts/data_validation]
[2025-01-25 15:48:13,117: INFO: main: >>>>>> stage Data Validation Stage completed <<<<<<<

x============x]
[2025-01-25 15:48:13,118: INFO: main: >>>>>> stage Data Transformation Stage started <<<<<<<<]
[2025-01-25 15:48:13,123: INFO: common: yaml file: config\config.yaml loaded sucessfully]
[2025-01-25 15:48:13,125: INFO: common: yaml file: params.yaml loaded sucessfully]
[2025-01-25 15:48:13,128: INFO: common: yaml file: schema.yaml loaded sucessfully]
[2025-01-25 15:48:13,129: INFO: common: Craeted directory at:artifacts]
[2025-01-25 15:48:13,130: INFO: common: Craeted directory at:artifacts/data_transformation]
[2025-01-25 15:48:13,163: INFO: data_transformation: Splitted data into training and test sets]
[2025-01-25 15:48:13,163: INFO: data_transformation: (1199, 12)]
[2025-01-25 15:48:13,164: INFO: data_transformation: (400, 12)]
[2025-01-25 15:48:13,165: INFO: main: >>>>>> stage Data Transformation Stage completed <<<<<<<

x============x]
[2025-01-25 15:48:13,165: INFO: main: >>>>>>>>>>> stageModel Trainer stage STARTED <<<<<<<<<<<]
[2025-01-25 15:48:13,170: INFO: common: yaml file: config\config.yaml loaded sucessfully]
[2025-01-25 15:48:13,171: INFO: common: yaml file: params.yaml loaded sucessfully]
[2025-01-25 15:48:13,174: INFO: common: yaml file: schema.yaml loaded sucessfully]
[2025-01-25 15:48:13,175: INFO: common: Craeted directory at:artifacts]
[2025-01-25 15:48:13,176: INFO: common: Craeted directory at:artifacts/model_trainer]
[2025-01-25 15:48:13,227: INFO: model_trainer: Model is saved at artifacts/model_trainer]
[2025-01-25 15:48:13,227: INFO: main: >>>>>>>> stageModel Trainer stage Completed <<<<<<

x============x]
[2025-01-25 15:48:13,228: INFO: main: >>>>>>>>>>> stageModel Evaluation stage STARTED <<<<<<<<<<<]
[2025-01-25 15:48:13,231: INFO: common: yaml file: config\config.yaml loaded sucessfully]
[2025-01-25 15:48:13,233: INFO: common: yaml file: params.yaml loaded sucessfully]
[2025-01-25 15:48:13,235: INFO: common: yaml file: schema.yaml loaded sucessfully]
[2025-01-25 15:48:13,236: INFO: common: Craeted directory at:artifacts]
[2025-01-25 15:48:13,237: INFO: common: Craeted directory at:artifacts/model_evaluation]
[2025-01-25 15:48:14,315: INFO: common: json file saved at:artifacts\model_evaluation\metrics.json]
[2025-01-25 15:48:24,548: INFO: main: >>>>>>>> stageModel Evaluation stage Completed <<<<<<

x============x]
[2025-01-25 15:52:34,394: INFO: main: >>>>>> stage Data Ingestion Stage started <<<<<<<<]
[2025-01-25 15:52:34,423: INFO: common: yaml file: config\config.yaml loaded sucessfully]
[2025-01-25 15:52:34,426: INFO: common: yaml file: params.yaml loaded sucessfully]
[2025-01-25 15:52:34,447: INFO: common: yaml file: schema.yaml loaded sucessfully]
[2025-01-25 15:52:34,449: INFO: common: Craeted directory at:artifacts]
[2025-01-25 15:52:34,452: INFO: common: Craeted directory at:artifacts/data_ingestion]
[2025-01-25 15:52:34,453: INFO: data_ingestion: File already exists]
[2025-01-25 15:52:34,488: INFO: main: >>>>>> stage Data Ingestion Stage completed <<<<<<<

x============x]
[2025-01-25 15:52:34,489: INFO: main: >>>>>> stage Data Validation Stage started <<<<<<<<]
[2025-01-25 15:52:34,499: INFO: common: yaml file: config\config.yaml loaded sucessfully]
[2025-01-25 15:52:34,502: INFO: common: yaml file: params.yaml loaded sucessfully]
[2025-01-25 15:52:34,507: INFO: common: yaml file: schema.yaml loaded sucessfully]
[2025-01-25 15:52:34,509: INFO: common: Craeted directory at:artifacts]
[2025-01-25 15:52:34,509: INFO: common: Craeted directory at:artifacts/data_validation]
[2025-01-25 15:52:34,570: INFO: main: >>>>>> stage Data Validation Stage completed <<<<<<<

x============x]
[2025-01-25 15:52:34,572: INFO: main: >>>>>> stage Data Transformation Stage started <<<<<<<<]
[2025-01-25 15:52:34,586: INFO: common: yaml file: config\config.yaml loaded sucessfully]
[2025-01-25 15:52:34,589: INFO: common: yaml file: params.yaml loaded sucessfully]
[2025-01-25 15:52:34,595: INFO: common: yaml file: schema.yaml loaded sucessfully]
[2025-01-25 15:52:34,597: INFO: common: Craeted directory at:artifacts]
[2025-01-25 15:52:34,599: INFO: common: Craeted directory at:artifacts/data_transformation]
[2025-01-25 15:52:34,782: INFO: data_transformation: Splitted data into training and test sets]
[2025-01-25 15:52:34,783: INFO: data_transformation: (1199, 12)]
[2025-01-25 15:52:34,786: INFO: data_transformation: (400, 12)]
[2025-01-25 15:52:34,788: INFO: main: >>>>>> stage Data Transformation Stage completed <<<<<<<

x============x]
[2025-01-25 15:52:34,789: INFO: main: >>>>>>>>>>> stageModel Trainer stage STARTED <<<<<<<<<<<]
[2025-01-25 15:52:34,798: INFO: common: yaml file: config\config.yaml loaded sucessfully]
[2025-01-25 15:52:34,800: INFO: common: yaml file: params.yaml loaded sucessfully]
[2025-01-25 15:52:34,806: INFO: common: yaml file: schema.yaml loaded sucessfully]
[2025-01-25 15:52:34,808: INFO: common: Craeted directory at:artifacts]
[2025-01-25 15:52:34,809: INFO: common: Craeted directory at:artifacts/model_trainer]
[2025-01-25 15:52:35,004: INFO: model_trainer: Model is saved at artifacts/model_trainer]
[2025-01-25 15:52:35,005: INFO: main: >>>>>>>> stageModel Trainer stage Completed <<<<<<

x============x]
[2025-01-25 15:52:35,005: INFO: main: >>>>>>>>>>> stageModel Evaluation stage STARTED <<<<<<<<<<<]
[2025-01-25 15:52:35,012: INFO: common: yaml file: config\config.yaml loaded sucessfully]
[2025-01-25 15:52:35,016: INFO: common: yaml file: params.yaml loaded sucessfully]
[2025-01-25 15:52:35,025: INFO: common: yaml file: schema.yaml loaded sucessfully]
[2025-01-25 15:52:35,028: INFO: common: Craeted directory at:artifacts]
[2025-01-25 15:52:35,029: INFO: common: Craeted directory at:artifacts/model_evaluation]
[2025-01-25 15:52:39,196: INFO: common: json file saved at:artifacts\model_evaluation\metrics.json]
[2025-01-25 15:53:10,670: INFO: main: >>>>>>>> stageModel Evaluation stage Completed <<<<<<

x============x]
